[package]
name = "is_tuesday"
version = "0.1.0"
edition = "2021"
authors = ["wildanrfq"]
license = "MIT"
description = "A crate to check if the current day is Tuesday."

[dependencies]
chrono = "0.4.24"